function sendMessage() {
    var userInput = document.getElementById("user-input").value;
    var history = document.getElementById("history");

    history.innerHTML += "<p><strong>Você:</strong> " + userInput + "</p>";

    var botResponse = generateResponse(userInput);

    history.innerHTML += "<p><strong>Chatbot:</strong> " + botResponse + "</p>";

    document.getElementById("user-input").value = "";
}

function generateResponse(userInput) {
    var lowerCaseInput = userInput.toLowerCase();

    if (lowerCaseInput.includes("olá") || lowerCaseInput.includes("oi") || lowerCaseInput.includes("oi!")) {
        var greetings = ["Olá! Como posso ajudar?", "Oi! Em que posso ser útil?", "Oi, tudo bem? Como posso te ajudar?"];
        return getRandomResponse(greetings);
    } else if (lowerCaseInput.includes("como você está?") || lowerCaseInput.includes("como vai você?")) {
        var howAreYouResponses = ["Estou bem, obrigado por perguntar!", "Me sinto bem, obrigado por perguntar.", "Estou bem, e você?"];
        return getRandomResponse(howAreYouResponses);
    } else if (lowerCaseInput.includes("quanto está o mistinho hoje?") || lowerCaseInput.includes("quanto está o mistinho hoje?")) {
        var howAreYouResponses = ["Hoje está R$3,00!", "Hoje está R$3,00!", "Hoje está R$3,00!"];
        return getRandomResponse(howAreYouResponses); 
    } else if (lowerCaseInput.includes("o que você tem a dizer sobre a apresentação?") || lowerCaseInput.includes("o que você tem a dizer sobre a apresentação?")) {
        var howAreYouResponses = ["Obrigado pela atenção!", "Obrigado pela atenção!", "Obrigado pela atenção!"];
        return getRandomResponse(howAreYouResponses); 
    } else if (lowerCaseInput.includes("quem é jesus cristo?") || lowerCaseInput.includes("quem é Jesus Cristo?")) {
        var howAreYouResponses = ["Nosso Senhor e Salvador!", "Nosso Senhor e Salvador!", "Nosso Senhor e Salvador!"];
        return getRandomResponse(howAreYouResponses); }
    
    else {
        var genericResponses = [
                "Não sei o que dizer sobre isso, me pergunte outra coisa...",
                "Desculpe, não tenho uma resposta para isso. Poderia tentar outra pergunta?",
                "Hmm, não estou certo sobre isso... Pode perguntar outra coisa?",
                "Estou aprendendo constantemente, mas essa pergunta é um pouco difícil para mim.",
                "Preciso de mais informações para responder a essa pergunta.",
                "Às vezes, é melhor buscar ajuda de um humano para essa questão.",
                "Isso é intrigante, mas está além do meu conhecimento atual.",
                "Gostaria de poder ajudar, mas esta é uma pergunta complicada para mim.",
                "Não tenho uma resposta para isso no momento.",
                "Hmm, essa é uma pergunta difícil, não tenho certeza de como responder.",
                "Parece que estou um pouco confuso com essa pergunta.",
                "Talvez eu precise de mais tempo para entender sua pergunta.",
                "Essa é uma questão desafiadora para mim, desculpe.",
                "Estou aqui para ajudar, mas essa pergunta me deixou perplexo.",
                "Não tenho certeza se consigo responder a isso corretamente.",
                "Hmm, isso é complicado demais para mim.",
                "Essa pergunta me deixou sem palavras.",
                "Parece que essa questão está além das minhas habilidades atuais.",
                "Não consigo encontrar uma resposta adequada para isso.",
                "Acho que não tenho informações suficientes para responder a essa pergunta.",
                "Hmm, parece que esta pergunta está me desafiando.",
                "Talvez eu precise de uma atualização de conhecimento para responder a isso.",
                "Não estou familiarizado com esse tópico, desculpe.",
                "Essa é uma pergunta que me deixa embaraçado.",
                "Parece que esta pergunta me pegou de surpresa.",
                "Sinto muito, mas não consigo fornecer uma resposta para isso.",
                "Essa pergunta me pegou desprevenido.",
                "Não consigo pensar em uma resposta para essa pergunta agora.",
                "Essa é uma questão complicada, preciso de mais tempo para pensar.",
                "Hmm, isso é um pouco fora da minha área de especialização.",
                "Essa pergunta é difícil, talvez você possa tentar perguntar de outra maneira?",
                "Não estou certo sobre isso, talvez eu precise de mais contexto.",
                "Essa pergunta me pegou de surpresa, não sei o que dizer.",
                "Hmm, parece que essa pergunta está além do meu alcance atual.",
                "Não consigo encontrar uma resposta satisfatória para essa pergunta.",
                "Talvez você precise reformular sua pergunta, estou tendo dificuldade em entender.",
                "Essa pergunta é um pouco complicada demais para mim, desculpe.",
                "Estou tentando acompanhar, mas essa pergunta é difícil de responder.",
                "Essa é uma pergunta desafiadora, estou tendo dificuldade em encontrar uma resposta.",
                "Essa pergunta me deixou perplexo, não consigo encontrar uma resposta adequada.",
                "Sinto muito, mas não consigo responder a essa pergunta no momento.",
                "Não tenho certeza se posso ajudar com isso, desculpe.",
                "Hmm, estou um pouco perdido com essa pergunta.",
                "Essa pergunta é um pouco fora do meu domínio, desculpe.",
                "Parece que estou tendo dificuldades para encontrar uma resposta para essa pergunta.",
                "Estou um pouco confuso com essa pergunta, desculpe.",
                "Essa pergunta é complicada, estou lutando para encontrar uma resposta.",
                "Desculpe, não consigo encontrar uma resposta para essa pergunta agora mesmo.",
                "Essa pergunta é um pouco complexa demais para mim, desculpe.",
                "Hmm, isso é difícil, não consigo responder agora.",
                "Estou tendo dificuldade em entender essa pergunta, desculpe.",
                "Essa pergunta me deixou perplexo, desculpe, não tenho uma resposta.",
                "Estou tendo problemas para responder a essa pergunta, desculpe.",
                "Parece que estou tendo dificuldades para encontrar uma resposta adequada.",
                "Essa pergunta me deixou um pouco confuso, desculpe.",
                "Hmm, isso é complicado demais para mim, desculpe.",
                "Não consigo encontrar uma resposta para essa pergunta, desculpe.",
                "Estou tendo dificuldade em encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é um pouco além da minha capacidade atual, desculpe.",
                "Desculpe, essa pergunta é um pouco complicada demais para mim.",
                "Parece que estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Estou um pouco perdido com essa pergunta, desculpe.",
                "Essa pergunta é difícil de responder, desculpe.",
                "Não consigo pensar em uma resposta para essa pergunta agora, desculpe.",
                "Estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Hmm, essa pergunta me pegou de surpresa, desculpe.",
                "Essa pergunta é um pouco complicada, estou tendo dificuldades para responder, desculpe.",
                "Não tenho uma resposta para essa pergunta, desculpe.",
                "Estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é um pouco fora do meu alcance, desculpe.",
                "Parece que estou tendo dificuldades para encontrar uma resposta adequada para essa pergunta, desculpe.",
                "Hmm, essa é uma pergunta difícil, estou tendo dificuldades para responder, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é um pouco complexa demais para mim, desculpe.",
                "Não tenho uma resposta adequada para essa pergunta, desculpe.",
                "Estou um pouco confuso com essa pergunta, desculpe.",
                "Essa pergunta é um pouco complicada demais para mim, desculpe.",
                "Hmm, não tenho certeza de como responder a essa pergunta, desculpe.",
                "Não consigo encontrar uma resposta adequada para essa pergunta no momento, desculpe.",
                "Essa pergunta é um pouco além do meu conhecimento atual, desculpe.",
                "Estou tendo dificuldades para responder a essa pergunta, desculpe.",
                "Hmm, essa pergunta me deixou perplexo, desculpe.",
                "Essa pergunta é um pouco difícil para mim, desculpe.",
                "Não consigo encontrar uma resposta para essa pergunta no momento, desculpe.",
                "Estou com dificuldades para responder a essa pergunta, desculpe.",
                "Essa pergunta é um pouco complicada, desculpe.",
                "Hmm, estou tendo dificuldade em encontrar uma resposta para essa pergunta, desculpe.",
                "Não tenho certeza de como responder a essa pergunta, desculpe.",
                "Essa pergunta está me desafiando um pouco, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada, desculpe.",
                "Essa pergunta é um pouco complicada demais para mim no momento, desculpe.",
                "Hmm, estou lutando para encontrar uma resposta adequada para essa pergunta, desculpe.",
                "Essa pergunta é difícil de responder, desculpe.",
                "Não estou certo sobre como responder a essa pergunta, desculpe.",
                "Essa pergunta está me deixando confuso, desculpe.",
                "Hmm, essa pergunta é um pouco complicada, desculpe.",
                "Estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é um pouco além das minhas habilidades no momento, desculpe.",
                "Estou tendo dificuldades para responder a essa pergunta, desculpe.",
                "Hmm, essa pergunta me pegou de surpresa, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é complicada demais para mim, desculpe.",
                "Não consigo pensar em uma resposta para essa pergunta agora, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada para essa pergunta, desculpe.",
                "Essa pergunta é um pouco complicada, desculpe.",
                "Hmm, essa é uma pergunta difícil, desculpe.",
                "Estou tendo dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é desafiadora, desculpe.",
                "Não tenho certeza de como responder a essa pergunta no momento, desculpe.",
                "Hmm, essa pergunta é um pouco complicada demais para mim, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é difícil de responder, desculpe.",
                "Não estou certo sobre como responder a essa pergunta, desculpe.",
                "Essa pergunta é complicada demais, desculpe.",
                "Hmm, estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta está me desafiando um pouco, desculpe.",
                "Estou tendo dificuldades para responder a essa pergunta, desculpe.",
                "Hmm, essa pergunta me pegou de surpresa, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é complicada demais para mim, desculpe.",
                "Não consigo pensar em uma resposta para essa pergunta agora, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada para essa pergunta, desculpe.",
                "Essa pergunta é um pouco complicada, desculpe.",
                "Hmm, essa é uma pergunta difícil, desculpe.",
                "Estou tendo dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é desafiadora, desculpe.",
                "Não tenho certeza de como responder a essa pergunta no momento, desculpe.",
                "Hmm, essa pergunta é um pouco complicada demais para mim, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é difícil de responder, desculpe.",
                "Não estou certo sobre como responder a essa pergunta, desculpe.",
                "Essa pergunta é complicada demais, desculpe.",
                "Hmm, estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta está me desafiando um pouco, desculpe.",
                "Estou tendo dificuldades para responder a essa pergunta, desculpe.",
                "Hmm, essa pergunta me pegou de surpresa, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é complicada demais para mim, desculpe.",
                "Não consigo pensar em uma resposta para essa pergunta agora, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada para essa pergunta, desculpe.",
                "Essa pergunta é um pouco complicada, desculpe.",
                "Hmm, essa é uma pergunta difícil, desculpe.",
                "Estou tendo dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é desafiadora, desculpe.",
                "Não tenho certeza de como responder a essa pergunta no momento, desculpe.",
                "Hmm, essa pergunta é um pouco complicada demais para mim, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é difícil de responder, desculpe.",
                "Não estou certo sobre como responder a essa pergunta, desculpe.",
                "Essa pergunta é complicada demais, desculpe.",
                "Hmm, estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta está me desafiando um pouco, desculpe.",
                "Estou tendo dificuldades para responder a essa pergunta, desculpe.",
                "Hmm, essa pergunta me pegou de surpresa, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é complicada demais para mim, desculpe.",
                "Não consigo pensar em uma resposta para essa pergunta agora, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada para essa pergunta, desculpe.",
                "Essa pergunta é um pouco complicada, desculpe.",
                "Hmm, essa é uma pergunta difícil, desculpe.",
                "Estou tendo dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é desafiadora, desculpe.",
                "Não tenho certeza de como responder a essa pergunta no momento, desculpe.",
                "Hmm, essa pergunta é um pouco complicada demais para mim, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é difícil de responder, desculpe.",
                "Não estou certo sobre como responder a essa pergunta, desculpe.",
                "Essa pergunta é complicada demais, desculpe.",
                "Hmm, estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta está me desafiando um pouco, desculpe.",
                "Estou tendo dificuldades para responder a essa pergunta, desculpe.",
                "Hmm, essa pergunta me pegou de surpresa, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é complicada demais para mim, desculpe.",
                "Não consigo pensar em uma resposta para essa pergunta agora, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada para essa pergunta, desculpe.",
                "Essa pergunta é um pouco complicada, desculpe.",
                "Hmm, essa é uma pergunta difícil, desculpe.",
                "Estou tendo dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é desafiadora, desculpe.",
                "Não tenho certeza de como responder a essa pergunta no momento, desculpe.",
                "Hmm, essa pergunta é um pouco complicada demais para mim, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é difícil de responder, desculpe.",
                "Não estou certo sobre como responder a essa pergunta, desculpe.",
                "Essa pergunta é complicada demais, desculpe.",
                "Hmm, estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta está me desafiando um pouco, desculpe.",
                "Estou tendo dificuldades para responder a essa pergunta, desculpe.",
                "Hmm, essa pergunta me pegou de surpresa, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é complicada demais para mim, desculpe.",
                "Não consigo pensar em uma resposta para essa pergunta agora, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada para essa pergunta, desculpe.",
                "Essa pergunta é um pouco complicada, desculpe.",
                "Hmm, essa é uma pergunta difícil, desculpe.",
                "Estou tendo dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é desafiadora, desculpe.",
                "Não tenho certeza de como responder a essa pergunta no momento, desculpe.",
                "Hmm, essa pergunta é um pouco complicada demais para mim, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é difícil de responder, desculpe.",
                "Não estou certo sobre como responder a essa pergunta, desculpe.",
                "Essa pergunta é complicada demais, desculpe.",
                "Hmm, estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta está me desafiando um pouco, desculpe.",
                "Estou tendo dificuldades para responder a essa pergunta, desculpe.",
                "Hmm, essa pergunta me pegou de surpresa, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é complicada demais para mim, desculpe.",
                "Não consigo pensar em uma resposta para essa pergunta agora, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada para essa pergunta, desculpe.",
                "Essa pergunta é um pouco complicada, desculpe.",
                "Hmm, essa é uma pergunta difícil, desculpe.",
                "Estou tendo dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é desafiadora, desculpe.",
                "Não tenho certeza de como responder a essa pergunta no momento, desculpe.",
                "Hmm, essa pergunta é um pouco complicada demais para mim, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é difícil de responder, desculpe.",
                "Não estou certo sobre como responder a essa pergunta, desculpe.",
                "Essa pergunta é complicada demais, desculpe.",
                "Hmm, estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta está me desafiando um pouco, desculpe.",
                "Estou tendo dificuldades para responder a essa pergunta, desculpe.",
                "Hmm, essa pergunta me pegou de surpresa, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é complicada demais para mim, desculpe.",
                "Não consigo pensar em uma resposta para essa pergunta agora, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada para essa pergunta, desculpe.",
                "Essa pergunta é um pouco complicada, desculpe.",
                "Hmm, essa é uma pergunta difícil, desculpe.",
                "Estou tendo dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é desafiadora, desculpe.",
                "Não tenho certeza de como responder a essa pergunta no momento, desculpe.",
                "Hmm, essa pergunta é um pouco complicada demais para mim, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é difícil de responder, desculpe.",
                "Não estou certo sobre como responder a essa pergunta, desculpe.",
                "Essa pergunta é complicada demais, desculpe.",
                "Hmm, estou com dificuldades para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta está me desafiando um pouco, desculpe.",
                "Estou tendo dificuldades para responder a essa pergunta, desculpe.",
                "Hmm, essa pergunta me pegou de surpresa, desculpe.",
                "Essa pergunta está me deixando um pouco confuso, desculpe.",
                "Estou lutando para encontrar uma resposta para essa pergunta, desculpe.",
                "Essa pergunta é complicada demais para mim, desculpe.",
                "Não consigo pensar em uma resposta para essa pergunta agora, desculpe.",
                "Estou com dificuldades para encontrar uma resposta adequada para essa pergunta, desculpe."
        ];
        return getRandomResponse(genericResponses);
    }
}

function getRandomResponse(responses) {
    var randomIndex = Math.floor(Math.random() * responses.length);
    return responses[randomIndex];
}
